/** @file
 *  @brief MAVLink comm protocol built from matrixpilot.xml
 *  @see http://mavlink.org
 */
#pragma once
 
#ifndef MAVLINK_VERSION_H
#define MAVLINK_VERSION_H

<<<<<<< HEAD
#define MAVLINK_BUILD_DATE "Tue Dec 10 2019"
=======
#define MAVLINK_BUILD_DATE "Fri Jul 17 2020"
>>>>>>> f90ef7c9 (autogenerated headers for rev https://github.com/mavlink/mavlink/tree/625b51afed651c4e7f38248a4443faa969506f3c)
#define MAVLINK_WIRE_PROTOCOL_VERSION "2.0"
#define MAVLINK_MAX_DIALECT_PAYLOAD_SIZE 255
 
#endif // MAVLINK_VERSION_H
